"""S-64 step 12 · backfill DRY RUN — read only. Builds reservation/1 (backfilled: true) for every trip item a Sasha
record points at that has no request yet, from that record and the item's own columns. Prints the count and the SQL."""
import asyncio, os, json, sys
sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parents[1]))
import asyncpg
from booking_signer import reservation as RS, optins as O, venue_read as V
from booking_signer.canonical import canonical_json

async def m():
    c = await asyncpg.connect(os.environ["DATABASE_URL"].replace("postgresql+asyncpg://", "postgresql://", 1), statement_cache_size=0)
    await c.set_type_codec("jsonb", encoder=json.dumps, decoder=json.loads, schema="pg_catalog")
    items = await c.fetch("""select t.id, t.type, t.status, t.provider_name, t.local_timezone, t.party_size,
                                    to_char(t.date_time at time zone t.local_timezone, 'YYYY-MM-DD"T"HH24:MI') as local_at, p.owner_id
                             from trip_items t join trips p on p.id = t.trip_id where t.request is null order by t.created_at""")
    built, skipped = [], []
    for it in items:
        src = None
        k = await c.fetchrow("select brief from booking_calls where trip_item_id = $1 order by created_at limit 1", it["id"])
        e = await c.fetchrow("select e.email, r.read from booking_emails e left join venue_reads r on r.read_id = e.read_id where e.trip_item_id = $1 limit 1", it["id"])
        l = await c.fetchrow("select r.read from booking_links l left join venue_reads r on r.read_id = l.read_id where l.trip_item_id = $1 limit 1", it["id"])
        n = await c.fetchrow("select guest_name, guest_email, guest_phone from booking_intents where trip_item_id = $1 limit 1", it["id"])
        contact, name, venue_ids, lang = {}, None, [], "en"
        if k:
            b = k["brief"]; src = "call"; name = b.get("name"); venue_ids = b.get("venue_ids") or []; lang = b.get("language") or "en"
            if b.get("phone"): contact["mobile_e164"] = b["phone"]
        elif e:
            src = "email"; name = None; contact["email"] = (e["email"] or {}).get("bcc")
            if e["read"]: venue_ids = O.venue_ids_of(e["read"]); lang = V.COUNTRIES.get(e["read"].get("country") or "", ("", "", "en"))[2]
        elif l:
            src = "link"
            if l["read"]: venue_ids = O.venue_ids_of(l["read"]); lang = V.COUNTRIES.get(l["read"].get("country") or "", ("", "", "en"))[2]
        elif n:
            src = "form"; name = n["guest_name"]; contact["email"] = n["guest_email"]
            # the form path records no language: the venue's own, from its timezone (as routes.py does)
            lang = next((cc[2] for cc in V.COUNTRIES.values() if cc[3] == it["local_timezone"]), "en")
            ph = "".join(ch for ch in str(n["guest_phone"] or "") if ch.isdigit() or ch == "+")
            if ph.startswith("+") and 9 <= len(ph) <= 16:
                contact["mobile_e164"] = ph       # only a number already international; nothing is guessed
        if src is None:
            skipped.append((str(it["id"]), "not a Sasha row (no call, email, link or form record)")); continue
        if name is None:
            skipped.append((str(it["id"]), f"{src}: the guest's name is not recorded on it — nothing is invented")); continue
        obj = {"schema": "reservation/1", "flow": "book", "backfilled": True,
               "who": {"name": name, "account_id": str(it["owner_id"]), "contact": {k2: v for k2, v in contact.items() if v}},
               "what": {"activity": "a table", "activity_venue_lang": RS.TABLE.get(lang.split("-")[0], "a table"), "category": "restaurant"},
               "where": {"venue_name": it["provider_name"], "timezone": it["local_timezone"] or "UTC", "venue_ids": venue_ids},
               "when": {"mode": "at", "at": it["local_at"]}, "how_many": {"count": it["party_size"], "unit": "people"}}
        try:
            o = RS.validate(obj)
            built.append((str(it["id"]), src, o, RS.sha256(o)))
        except Exception as ex:
            skipped.append((str(it["id"]), f"{src}: {ex}"))
    await c.close()
    print(f"items without a request: {len(items)} · would backfill: {len(built)} · left alone: {len(skipped)}")
    for i, src, o, sha in built:
        print(f"  BUILD {i[:8]} from {src}: {o['where']['venue_name']} · {o['when']['at']} · {o['how_many']['count']} · {o['who']['name']}")
    for i, why in skipped:
        print(f"  SKIP  {i[:8]}: {why}")
    sql = ["-- S-64 step 12 · backfill reservation/1 for pre-S-64 rows (backfilled: true). Generated by a read-only dry run.",
           "-- Only rows still without a request are touched; channel rows are NOT given a request_sha256 — they did not carry one.",
           "-- PREVIEW (read only):",
           "select id, provider_name, status, request is null as no_request from public.trip_items where id in (" + ", ".join(f"'{i}'" for i, *_ in built) + ");",
           "begin;"]
    for i, src, o, sha in built:
        lit = canonical_json(o).replace("'", "''")
        sql.append(f"update public.trip_items set request = '{lit}'::jsonb, request_sha256 = '{sha}', request_schema = 'reservation/1' where id = '{i}' and request is null;")
    sql += [f"select 'backfilled rows' as check, count(*) = {len(built)} as ok from public.trip_items where request->>'backfilled' = 'true';", "commit;"]
    open(sys.argv[1] if len(sys.argv) > 1 else "012_backfill_request.sql", "w").write("\n".join(sql) + "\n")
    print("SQL written:", len(sql), "lines")

asyncio.run(m())
