#!/usr/bin/env bash
# end_session.sh — Generate and commit a session handoff document using Claude
# Usage: ./scripts/end_session.sh
# Run from the repo root. Requires ANTHROPIC_API_KEY in environment.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$REPO_ROOT/docs/session_current.md"

echo "🔍 Gathering project state..."

# ── Git context ──────────────────────────────────────────────────────────────
GIT_LOG=$(git -C "$REPO_ROOT" log --oneline -20)
GIT_CHANGED=$(git -C "$REPO_ROOT" diff HEAD~1 --name-only 2>/dev/null || echo "(no previous commit)")
GIT_BRANCH=$(git -C "$REPO_ROOT" branch --show-current)
GIT_LAST_COMMIT=$(git -C "$REPO_ROOT" log -1 --pretty="%h %s")

# ── Key file contents ────────────────────────────────────────────────────────
read_file() {
  local path="$REPO_ROOT/$1"
  if [[ -f "$path" ]]; then
    echo "=== $1 ==="
    cat "$path"
    echo ""
  else
    echo "=== $1 === (FILE NOT FOUND)"
  fi
}

SASHA_AVATAR=$(read_file "frontend/app/components/SashaAvatar.tsx")
VOICE_BUTTON=$(read_file "frontend/app/components/VoiceButton.tsx")
VIETNAM_PAGE=$(read_file "frontend/app/vietnam/page.tsx")
CONDUCTOR=$(read_file "backend/app/services/conductor.py")
EXISTING_HANDOFF=""
if [[ -f "$REPO_ROOT/docs/new_chat_handoff.md" ]]; then
  EXISTING_HANDOFF=$(cat "$REPO_ROOT/docs/new_chat_handoff.md")
fi

# ── Assemble payload ─────────────────────────────────────────────────────────
CONTEXT=$(cat <<CONTEXT
GIT BRANCH: $GIT_BRANCH
LAST COMMIT: $GIT_LAST_COMMIT

RECENT COMMITS (last 20):
$GIT_LOG

FILES CHANGED IN LAST COMMIT:
$GIT_CHANGED

--- KEY FILE CONTENTS ---

$SASHA_AVATAR

$VOICE_BUTTON

$VIETNAM_PAGE

$CONDUCTOR

--- EXISTING HANDOFF DOCUMENT (new_chat_handoff.md) ---
$EXISTING_HANDOFF
CONTEXT
)

PROMPT="You are a session continuity agent for a software project called Kanoe / Sasha Travel. Read the following git history and key file contents carefully. Write a structured handoff document (Markdown) that a new Claude instance can read to understand exactly where this project is, what is working, what is broken, what was changed today, and what to do next. Be specific about file states and do not lose any technical detail. Include: (1) current state of the voice pipeline with exact component responsibilities, (2) HeyGen integration status and any known bugs, (3) all 23 agents and conductor architecture, (4) database schema status, (5) deployment URLs, (6) env var locations, (7) next priorities in order, (8) rules/gotchas that caused bugs before. Format for a developer picking this up cold."

echo "🤖 Calling Claude to generate session_current.md..."

# ── Call Anthropic API ───────────────────────────────────────────────────────
RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -H "content-type: application/json" \
  -d "$(jq -n \
    --arg model "claude-opus-4-8" \
    --arg prompt "$PROMPT" \
    --arg context "$CONTEXT" \
    '{
      model: $model,
      max_tokens: 4096,
      messages: [{
        role: "user",
        content: ($prompt + "\n\n" + $context)
      }]
    }'
  )")

# ── Extract text from response ───────────────────────────────────────────────
CONTENT=$(echo "$RESPONSE" | jq -r '.content[0].text // empty')

if [[ -z "$CONTENT" ]]; then
  echo "❌ Claude returned no content. Raw response:"
  echo "$RESPONSE"
  exit 1
fi

# ── Write output ─────────────────────────────────────────────────────────────
echo "# Session State — $(date '+%Y-%m-%d %H:%M')" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "_Auto-generated by scripts/end_session.sh using Claude. Do not edit manually._" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "$CONTENT" >> "$OUTPUT"

echo "✅ Written: docs/session_current.md"

# ── Commit and push ───────────────────────────────────────────────────────────
git -C "$REPO_ROOT" add docs/session_current.md
git -C "$REPO_ROOT" commit -m "chore: update session_current.md [auto]"
git -C "$REPO_ROOT" push

echo "✅ Committed and pushed docs/session_current.md"
echo ""
echo "To start the next chat, paste this into Claude:"
echo "  Read docs/session_current.md and the files it references in https://github.com/tylerwarren-droid/Sasha-travel- then pick up where we left off."
